-- MySQL Script generated by MySQL Workbench
-- Tue May  3 11:34:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Service_station
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Service_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Service_station` DEFAULT CHARACTER SET utf8 ;
USE `Service_station` ;

-- -----------------------------------------------------
-- Table `Service_station`.`Autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Autos` (
  `StateNumber` INT NOT NULL,
  `Model` VARCHAR(45) NULL,
  PRIMARY KEY (`StateNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Sales` (
  `idSales` INT NOT NULL,
  `Service` VARCHAR(45) NULL,
  `Sale` VARCHAR(45) NULL,
  `Conditions` VARCHAR(45) NULL,
  PRIMARY KEY (`idSales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Clients` (
  `idClients` INT NOT NULL,
  `Name` VARCHAR(15) NULL,
  `FirstName` VARCHAR(45) NULL,
  `Autos_StateNumber` INT NOT NULL,
  `Sales_idSales` INT NOT NULL,
  PRIMARY KEY (`idClients`),
  INDEX `fk_Clients_Autos1_idx` (`Autos_StateNumber` ASC) VISIBLE,
  INDEX `fk_Clients_Sales1_idx` (`Sales_idSales` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Autos1`
    FOREIGN KEY (`Autos_StateNumber`)
    REFERENCES `Service_station`.`Autos` (`StateNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_Sales1`
    FOREIGN KEY (`Sales_idSales`)
    REFERENCES `Service_station`.`Sales` (`idSales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Garages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Garages` (
  `idGarages` INT NOT NULL,
  `Adress` VARCHAR(45) NULL,
  PRIMARY KEY (`idGarages`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Salaries` (
  `idSalaries` INT NOT NULL,
  `Employeers` VARCHAR(45) NULL,
  `Salary` VARCHAR(45) NULL,
  PRIMARY KEY (`idSalaries`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Employeers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Employeers` (
  `idEmployeers` INT NOT NULL,
  `Employeer` VARCHAR(45) NULL,
  `Garages_idGarages` INT NOT NULL,
  `Salaries_idSalaries` INT NOT NULL,
  PRIMARY KEY (`idEmployeers`),
  INDEX `fk_Employeers_Garages1_idx` (`Garages_idGarages` ASC) VISIBLE,
  INDEX `fk_Employeers_Salaries1_idx` (`Salaries_idSalaries` ASC) VISIBLE,
  CONSTRAINT `fk_Employeers_Garages1`
    FOREIGN KEY (`Garages_idGarages`)
    REFERENCES `Service_station`.`Garages` (`idGarages`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employeers_Salaries1`
    FOREIGN KEY (`Salaries_idSalaries`)
    REFERENCES `Service_station`.`Salaries` (`idSalaries`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Admins` (
  `idAdmins` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `TelefonNumber` VARCHAR(45) NULL,
  `Employeers_idEmployeers` INT NOT NULL,
  PRIMARY KEY (`idAdmins`),
  INDEX `fk_Admins_Employeers1_idx` (`Employeers_idEmployeers` ASC) VISIBLE,
  CONSTRAINT `fk_Admins_Employeers1`
    FOREIGN KEY (`Employeers_idEmployeers`)
    REFERENCES `Service_station`.`Employeers` (`idEmployeers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Costs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Costs` (
  `idCosts` INT NOT NULL,
  `Services` VARCHAR(45) NULL,
  `Cost` DOUBLE NULL,
  PRIMARY KEY (`idCosts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`TimeToWork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`TimeToWork` (
  `idTime` INT NOT NULL,
  `TimeToWork` DOUBLE NULL,
  PRIMARY KEY (`idTime`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Sevices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Sevices` (
  `idSevices` INT NOT NULL,
  `Sevices` VARCHAR(45) NULL,
  `Costs_idCosts` INT NOT NULL,
  `TimeToWork_idTime` INT NOT NULL,
  PRIMARY KEY (`idSevices`),
  INDEX `fk_Sevices_Costs1_idx` (`Costs_idCosts` ASC) VISIBLE,
  INDEX `fk_Sevices_TimeToWork1_idx` (`TimeToWork_idTime` ASC) VISIBLE,
  CONSTRAINT `fk_Sevices_Costs1`
    FOREIGN KEY (`Costs_idCosts`)
    REFERENCES `Service_station`.`Costs` (`idCosts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sevices_TimeToWork1`
    FOREIGN KEY (`TimeToWork_idTime`)
    REFERENCES `Service_station`.`TimeToWork` (`idTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`ActiveTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`ActiveTasks` (
  `idActiveTask` INT NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `Employeers_idEmployeers` INT NOT NULL,
  `Sevices_idSevices` INT NOT NULL,
  PRIMARY KEY (`idActiveTask`),
  INDEX `fk_ActiveTasks_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  INDEX `fk_ActiveTasks_Employeers1_idx` (`Employeers_idEmployeers` ASC) VISIBLE,
  INDEX `fk_ActiveTasks_Sevices1_idx` (`Sevices_idSevices` ASC) VISIBLE,
  CONSTRAINT `fk_ActiveTasks_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `Service_station`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActiveTasks_Employeers1`
    FOREIGN KEY (`Employeers_idEmployeers`)
    REFERENCES `Service_station`.`Employeers` (`idEmployeers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActiveTasks_Sevices1`
    FOREIGN KEY (`Sevices_idSevices`)
    REFERENCES `Service_station`.`Sevices` (`idSevices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Diagnosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Diagnosts` (
  `idDiagnosts` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `TelefonNumber` VARCHAR(45) NULL,
  `Employeers_idEmployeers` INT NOT NULL,
  PRIMARY KEY (`idDiagnosts`),
  INDEX `fk_Diagnosts_Employeers1_idx` (`Employeers_idEmployeers` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnosts_Employeers1`
    FOREIGN KEY (`Employeers_idEmployeers`)
    REFERENCES `Service_station`.`Employeers` (`idEmployeers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Materials` (
  `idMaterials` INT NOT NULL,
  `Supplier` VARCHAR(45) NULL,
  `Materials` VARCHAR(45) NULL,
  PRIMARY KEY (`idMaterials`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Suppliers` (
  `idSuppliers` INT NOT NULL,
  `Supplier` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  PRIMARY KEY (`idSuppliers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Masters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Masters` (
  `idMasters` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `TelefonNumber` VARCHAR(45) NULL,
  `Employeers_idEmployeers` INT NOT NULL,
  PRIMARY KEY (`idMasters`),
  INDEX `fk_Masters_Employeers1_idx` (`Employeers_idEmployeers` ASC) VISIBLE,
  CONSTRAINT `fk_Masters_Employeers1`
    FOREIGN KEY (`Employeers_idEmployeers`)
    REFERENCES `Service_station`.`Employeers` (`idEmployeers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Service_station`.`Suppliers_has_Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service_station`.`Suppliers_has_Materials` (
  `Suppliers_idSuppliers` INT NOT NULL,
  `Materials_idMaterials` INT NOT NULL,
  PRIMARY KEY (`Suppliers_idSuppliers`, `Materials_idMaterials`),
  INDEX `fk_Suppliers_has_Materials_Materials1_idx` (`Materials_idMaterials` ASC) VISIBLE,
  INDEX `fk_Suppliers_has_Materials_Suppliers_idx` (`Suppliers_idSuppliers` ASC) VISIBLE,
  CONSTRAINT `fk_Suppliers_has_Materials_Suppliers`
    FOREIGN KEY (`Suppliers_idSuppliers`)
    REFERENCES `Service_station`.`Suppliers` (`idSuppliers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Suppliers_has_Materials_Materials1`
    FOREIGN KEY (`Materials_idMaterials`)
    REFERENCES `Service_station`.`Materials` (`idMaterials`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
