-- MySQL Script generated by MySQL Workbench
-- Wed May  4 17:54:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ServiceStation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ServiceStation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Service` DEFAULT CHARACTER SET utf8 ;
USE `Service` ;

-- -----------------------------------------------------
-- Table `ServiceStation`.`Autos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Auto` (
  `StateNumber` INT NOT NULL,
  `Model` VARCHAR(45) NULL,
  PRIMARY KEY (`StateNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Clients` (
  `idClients` INT GENERATED ALWAYS AS () VIRTUAL,
  `Name` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `TelefonNumber` VARCHAR(45) NULL,
  `Auto_StateNumber` INT NOT NULL,
  PRIMARY KEY (`idClients`),
  INDEX `fk_Clients_Auto1_idx` (`Auto_StateNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Clients_Auto1`
    FOREIGN KEY (`Auto_StateNumber`)
    REFERENCES `Service`.`Auto` (`StateNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Services` (
  `idServices` INT NOT NULL,
  `Service` VARCHAR(45) NULL,
  `TimeToWork` DOUBLE NULL,
  PRIMARY KEY (`idServices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Sales` (
  `idSales` INT NOT NULL,
  `Sale` VARCHAR(45) NULL,
  `Conditions` VARCHAR(45) NULL,
  `Services_idServices` INT NOT NULL,
  PRIMARY KEY (`idSales`),
  INDEX `fk_Sales_Services1_idx` (`Services_idServices` ASC) VISIBLE,
  CONSTRAINT `fk_Sales_Services1`
    FOREIGN KEY (`Services_idServices`)
    REFERENCES `Service`.`Services` (`idServices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Salaries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Salaries` (
  `idSalary` INT NOT NULL,
  `Employeer` VARCHAR(45) NULL,
  `Salary` DOUBLE NULL,
  PRIMARY KEY (`idSalary`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Garages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Garages` (
  `idGarage` INT NOT NULL,
  `Adress` VARCHAR(45) NULL,
  `MaxWorkers` INT NULL,
  PRIMARY KEY (`idGarage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Employeers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Employeers` (
  `idEmployeers` INT NOT NULL,
  `Employeer` VARCHAR(45) NULL,
  `Salaries_idSalary` INT NOT NULL,
  `Garages_idGarage` INT NOT NULL,
  PRIMARY KEY (`idEmployeers`),
  INDEX `fk_Employeers_Salaries1_idx` (`Salaries_idSalary` ASC) VISIBLE,
  INDEX `fk_Employeers_Garages1_idx` (`Garages_idGarage` ASC) VISIBLE,
  CONSTRAINT `fk_Employeers_Salaries1`
    FOREIGN KEY (`Salaries_idSalary`)
    REFERENCES `Service`.`Salaries` (`idSalary`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employeers_Garages1`
    FOREIGN KEY (`Garages_idGarage`)
    REFERENCES `Service`.`Garages` (`idGarage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Masters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Masters` (
  `idMasters` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `TelefonNumber` VARCHAR(45) NULL,
  `Employeers_idEmployeers` INT NOT NULL,
  PRIMARY KEY (`idMasters`),
  INDEX `fk_Masters_Employeers1_idx` (`Employeers_idEmployeers` ASC) VISIBLE,
  CONSTRAINT `fk_Masters_Employeers1`
    FOREIGN KEY (`Employeers_idEmployeers`)
    REFERENCES `Service`.`Employeers` (`idEmployeers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Diagnosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Diagnosts` (
  `idDiagnosts` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `TelefonNumber` VARCHAR(45) NULL,
  `Employeers_idEmployeers` INT NOT NULL,
  PRIMARY KEY (`idDiagnosts`),
  INDEX `fk_Diagnosts_Employeers1_idx` (`Employeers_idEmployeers` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnosts_Employeers1`
    FOREIGN KEY (`Employeers_idEmployeers`)
    REFERENCES `Service`.`Employeers` (`idEmployeers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`ActiveTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`ActiveTasks` (
  `idActiveTasks` INT NOT NULL,
  `Employeers_idEmployeers` INT NOT NULL,
  `Services_idServices` INT NOT NULL,
  `Clients_idClients` INT NOT NULL,
  PRIMARY KEY (`idActiveTasks`),
  INDEX `fk_ActiveTasks_Employeers_idx` (`Employeers_idEmployeers` ASC) VISIBLE,
  INDEX `fk_ActiveTasks_Services1_idx` (`Services_idServices` ASC) VISIBLE,
  INDEX `fk_ActiveTasks_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  CONSTRAINT `fk_ActiveTasks_Employeers`
    FOREIGN KEY (`Employeers_idEmployeers`)
    REFERENCES `Service`.`Employeers` (`idEmployeers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActiveTasks_Services1`
    FOREIGN KEY (`Services_idServices`)
    REFERENCES `Service`.`Services` (`idServices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ActiveTasks_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `Service`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`TimeToWork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`TimeToWork` (
  `idTime` INT NOT NULL,
  `TimeToWork` DOUBLE NULL,
  `Services_idServices` INT NOT NULL,
  PRIMARY KEY (`idTime`),
  INDEX `fk_TimeToWork_Services1_idx` (`Services_idServices` ASC) VISIBLE,
  CONSTRAINT `fk_TimeToWork_Services1`
    FOREIGN KEY (`Services_idServices`)
    REFERENCES `Service`.`Services` (`idServices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Costs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Costs` (
  `idCosts` INT NOT NULL,
  `Services` VARCHAR(45) NULL,
  `Costs` VARCHAR(45) NULL,
  `TimeToWork_idTime` INT NOT NULL,
  PRIMARY KEY (`idCosts`),
  INDEX `fk_Costs_TimeToWork1_idx` (`TimeToWork_idTime` ASC) VISIBLE,
  CONSTRAINT `fk_Costs_TimeToWork1`
    FOREIGN KEY (`TimeToWork_idTime`)
    REFERENCES `Service`.`TimeToWork` (`idTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Admins` (
  `idAdmins` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `FirstName` VARCHAR(45) NULL,
  `TelefonNumber` VARCHAR(45) NULL,
  `Employeers_idEmployeers` INT NOT NULL,
  PRIMARY KEY (`idAdmins`),
  INDEX `fk_Admins_Employeers1_idx` (`Employeers_idEmployeers` ASC) VISIBLE,
  CONSTRAINT `fk_Admins_Employeers1`
    FOREIGN KEY (`Employeers_idEmployeers`)
    REFERENCES `Service`.`Employeers` (`idEmployeers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Materials` (
  `idMaterials` INT NOT NULL,
  `Supplier` VARCHAR(45) NULL,
  `Materials` VARCHAR(45) NULL,
  PRIMARY KEY (`idMaterials`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Suppliers` (
  `idSuppliers` INT NOT NULL,
  `Supplier` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  PRIMARY KEY (`idSuppliers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ServiceStation`.`Materials_has_Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Service`.`Materials_has_Suppliers` (
  `Materials_idMaterials` INT NOT NULL,
  `Suppliers_idSuppliers` INT NOT NULL,
  `Costs_idCosts` INT NOT NULL,
  PRIMARY KEY (`Materials_idMaterials`, `Suppliers_idSuppliers`),
  INDEX `fk_Materials_has_Suppliers_Suppliers1_idx` (`Suppliers_idSuppliers` ASC) VISIBLE,
  INDEX `fk_Materials_has_Suppliers_Materials1_idx` (`Materials_idMaterials` ASC) VISIBLE,
  INDEX `fk_Materials_has_Suppliers_Costs1_idx` (`Costs_idCosts` ASC) VISIBLE,
  CONSTRAINT `fk_Materials_has_Suppliers_Materials1`
    FOREIGN KEY (`Materials_idMaterials`)
    REFERENCES `Service`.`Materials` (`idMaterials`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_has_Suppliers_Suppliers1`
    FOREIGN KEY (`Suppliers_idSuppliers`)
    REFERENCES `Service`.`Suppliers` (`idSuppliers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_has_Suppliers_Costs1`
    FOREIGN KEY (`Costs_idCosts`)
    REFERENCES `Service`.`Costs` (`idCosts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
